- name: Setup CargoFL environment
  hosts: all
  become: true

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - libmysqlclient-dev
          - libcurl4-openssl-dev
          - libzbar0
          - build-essential
          - libpoppler-cpp-dev
          - pkg-config
          - python3-dev
          - python3-certbot-nginx
          - figlet
          - prometheus-node-exporter
        state: present

    - name: Generate locale
      command: locale-gen "en_IN.UTF-8"

    - name: Set timezone
      command: timedatectl set-timezone Asia/Kolkata

    - name: Set hostname
      hostname:
        name: CargoFL

    - name: Clone private CargoFL repository
      command: git clone https://Ananthuaxd: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@github.com/innoctive/cargofl.git /home/innoctive/cargofl
      args:
        creates: /home/innoctive/cargofl

    - name: Install Python and virtualenv
      apt:
        name: ['python3', 'python3-venv']
        state: present


    - name: Create the virtual environment
      command: python3 -m venv /home/innoctive/venv
      args:
        creates: /home/innoctive/venv

    - name: Set permissions for venv and cargofl folders
      command: sudo chown -R innoctive:innoctive /home/innoctive/venv /home/innoctive/cargofl
      become: true


    - name: Set virtual environment variables for subsequent tasks
      set_fact:
        venv_activate: "source /home/innoctive/venv/bin/activate"

    - name: Upgrade pip
      pip:
        name: pip
        version: 21.0.1
        state: present
      become_user: innoctive
      environment:
        PATH: "/home/innoctive/venv/bin:{{ ansible_env.PATH }}"

    - name: Install Python dependencies
      pip:
        requirements: /home/innoctive/cargofl/requirements.txt
        virtualenv: /home/innoctive/venv
      become_user: innoctive

    - name: Configure Nginx
      copy:
        src: /home/ananthu/cargofl.conf
        dest: /etc/nginx/sites-enabled/cargofl.conf

    - name: Configure CargoFL service
      copy:
        src: /home/ananthu/cargofl.service
        dest: /etc/systemd/system/cargofl.service

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Restart CargoFL service
      service:
        name: cargofl
        state: restarted
        enabled: yes
