---
user: innoctive
password: '$6$Jiyjh1y4g6Z$ksDhUeppjltzHg5yxNHu7A/YBCsdyywbdTIfsB1I9puBaIRjZN/vAvKwF08WVB05qGipwWS2zMhR5m3WgmlKV0'
hostname: CargoFL
banner: Test
gitbranch: dtplus 
packages:
  - nginx
  - nginx-extras
  - python3
  - python3-pip
  - python3-venv
  - libmysqlclient-dev
  - libcurl4-openssl-dev
  - libzbar0
  - build-essential
  - libpoppler-cpp-dev
  - pkg-config
  - python3-dev
  - python3-certbot-nginx
  - prometheus-node-exporter

