- name: Start all instances except admin
  hosts: localhost
  gather_facts: False

  vars:
    ec2_region: ""
    admin_instance_id: ""
    aws_access_key: ""
    aws_secret_key: ""

  tasks:
    - name: Get instance facts
      ec2_instance_facts:
        region: "{{ ec2_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2_facts

    - name: Exclude admin instance
      set_fact:
        excluded_instance_ids: "{{ [admin_instance_id] }}"

    - name: Filter instances to start
      set_fact:
        instances_to_start: "{{ ec2_facts.instances | rejectattr('instance_id', 'equalto', admin_instance_id) | list }}"

    - name: Start instances
      ec2:
        region: "{{ ec2_region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: running
        instance_ids: "{{ instances_to_start | map(attribute='instance_id') | list }}"
      register: started_instances

    - name: Print started instances
      debug:
        var: started_instances
