# This playbook is to stop all ec2 instances except admin ec2 instance"
---
- name: Start EC2 instances
  hosts: localhost
  gather_facts: no
  vars:
    region: "{{ extra_vars.region }}"

  tasks:
    - name: Retrieve EC2 instances
      ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "*"
      register: ec2_info

    - name: Start EC2 instances
      ec2:
        region: "{{ region }}"
        instance_ids: "{{ item.instance_id }}"
        state: stopped
      with_items:
        - "{{ ec2_info.instances }}"
      when: "'admin' not in item.tags.Name"
