---
- name: Stop instances
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'i-0deb93534ed7604dd'
    region: ap-south-1
  tasks:
    - name: Stop the feature instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        state: stopped
        wait: True
